### ISSUE TITLE
Can not return a merged object via Object.assign within entity.set()

### ISSUE THREAD

**Issue by Devric** [arnelenero/simpler-state#11]
**Describe the bug**
entity.set does not work if returning a merged object with Object.assign

**To Reproduce**

```
const obj = entity({ x:1 })

var dataToBeUpdated = { x:2, y:1 }

const updateDoesNotWork = data => {
    obj.set( value => {
        return Object.assign(value, data)
    })
}

const updateWorks = data => {
    obj.set( value => {
        return {
            ...value,
           ...data
        }
    })    
}
```

**Expected behavior**
Both scenario should work

**Comment by arnelenero** [comment]
Hi.  Those 2 are not equivalent.  The `Object.assign()` one is mutating the original object, then returns the same object.  Can you try this instead?
```js
return Object.assign({}, value, data)
```

**Comment by arnelenero** [comment]
Closing issue as this does not appear to be a problem with the library at all.  Please see my comment above.
